name: Release when updated

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  part0:
    uses: ./.github/workflows/build.yml
    with:
      name: Part0
      file: ./part0-for-testing/numbertheory101_part0

  part1_picture:
    uses: ./.github/workflows/build.yml
    with:
      name: division_structure
      file: ./part1/pics/division_structure

  part1:
    needs: [part1_picture]
    uses: ./.github/workflows/build.yml
    with:
      name: Part1
      file: ./part1/numbertheory101_part1
      shell_escape: true
      need: division_structure
      need_dir: ./part1/pics/

  part2:
    uses: ./.github/workflows/build.yml
    with:
      name: Part2
      file: ./part2/numbertheory101_part2
      shell_escape: true

  release:
    needs: [part0, part1, part2]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get commit id
        run: echo "release_id=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: release/${{ env.release_id }}

      - name: Fetch results
        uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Part0/Part0.pdf
            ./Part1/Part1.pdf
            ./Part2/Part2.pdf
          body: 由 GitHub Actions 自动发布，对应 commit ${{ env.release_id }}。
          name: Release ${{ env.release_id }}
          tag_name: release/${{ env.release_id }}
